import Link from "next/link";
import "./globals.css";
import { Control } from "./Control";

export const metadata = {
  title: "WEB tutorial",
  description: "Generated by egoing",
};

export default async function RootLayout({ children }) {
  const topics = await fetch(`${process.env.NEXT_PUBLIC_API_URL}topics`, { cache: "no-cache" }).then((res) =>
    res.json()
  );

  return (
    <html>
      <body>
        <h1>
          <Link href="/">GO TO HOME</Link>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control></Control>
      </body>
    </html>
  );
}
